name: shelf_paginate
description: Page a json file.
version: 1.0.0
homepage: https://github.com/jhecksonSa/shelf_paginate

environment:
  sdk: '>=2.17.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {shelf: ^1.3.2}
